version: '2'
services:
    web:
        build: .
        container_name: "auth_service"
        ports:
            - "5000:5000"
        environment:
            - MONGODB=mongodb://accountUser:password@mongo:27017/
            - MONGODB_wauth=mongodb://mongo:27017/
        volumes:
            - .:/code
        links:
            - mongo
        depends_on:
            - mongo
    mongo:
        image: mongo:latest
        container_name: "mongo"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/var/log/mongodb/log.txt # --quiet
